name: "godot-ci export"
on:
  push:
    tags:
      - '*'

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: game-jam-template
  # To get tag, use $GITHUB_REF_NAME
  PROJECT_PATH: game-jam-template

jobs:
  export-web:
    name: Web Export and Upload
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    container:
      image: docker://barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
          # lfs: true
      - name: GCP Auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          # service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          rm -rf build
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --export-release "Web" ../build/web/index.html
      - name: Compress Web Build
        run: |
          mkdir -v build/zip
          zip -qq -r "build/zip/${EXPORT_NAME}-${GITHUB_REF_NAME}.zip" "build/web/*"
      - name: Upload to GCP
        uses: google-github-actions/upload-cloud-storage@v2
        env:
          GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
        with:
          path: "build/zip"
          destination: "${GCP_BUCKET_NAME}"
