name: "godot-ci export"
on:
  push:
    tags:
      - '*'

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: game-jam-template
  # To get tag, use $GITHUB_REF_NAME
  PROJECT_PATH: game-jam-template

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
          # lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          rm -rf build/web
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --export-release "Web" ../build/web/index.html
          cd -
      - name: Compress Web Build
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r "build/web/${EXPORT_NAME}-${GITHUB_REF_NAME}.zip" build/web/*
            
