name: "tag-release export and upload"
on:
  push:
    tags:
      - '*'

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: game-jam-template
  PROJECT_PATH: game-jam-template
  ENV_ITCH_GAME: 2hg-test

jobs:
  export-web:
    name: Web Export and Upload
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    container:
      image: docker://barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
          # lfs: true
      - name: GCP Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          rm -rf build
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --export-release "Web" ../build/web/index.html
      - name: Compress Web Build
        run: |
          mkdir -v build/zip
          cd build/web
          zip -qq -r "../zip/${EXPORT_NAME}-${GITHUB_REF_NAME}.zip" *
      - name: Upload to GCP
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: "build/zip"
          destination: ${{ secrets.GCP_BUCKET_NAME }}

  upload-to-itch:
    name: Upload Builds to Itch
    needs: export-web
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
          # lfs: true
      - name: GCP Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Download Web Build from GCP
        run: |
          gcloud storage cp "gs://${{ secrets.GCP_BUCKET_NAME }}/zip/${EXPORT_NAME}-${GITHUB_REF_NAME}.zip" .
      - name: Upload Web BUild to itch.io
        uses: yeslayla/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5-release
          ITCH_GAME: $ENV_ITCH_GAME
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: ${EXPORT_NAME}-${GITHUB_REF_NAME}.zip
          VERSION: $GITHUB_REF_NAME
